### PR TITLE
Allow disabling hover by props

### PR DESCRIPTION
**Pull request by dimkarakostas**
Show text on hover by default, disable by explicitly adding "alloHover={false}"

### CODE REVIEW

**Comment by swapnil95** [comment]
Thanks a lot for this pull request. It saved me a lot of time. I think this should be merged

**Comment by dimkarakostas** [comment]
@chadoh have you reviewed this PR? Could you please give some feedback on any needed changes or else merge it and update the npm package?

**Comment by chadoh** [comment]
Sorry I missed this until now, y'all! 

PS I think [emoji-mart](https://missive.github.io/emoji-mart/) looks great and plan to switch my own projects over to it, and away from this thing I built here, fairly soon. Y'all may also enjoy it. If you think there's a good reason to keep `react-emoji-picker` around, I'd be curious to hear your reasons.

**Comment by dimkarakostas** [comment]
I like to show only the emojis and the categories, so at first glance I'm not sure if Emoji Mart allows to hide the Search Bar, Frequently Used and Title. I'll be sure to check it out though, thanks for the recommendation.

**Pull request merged**
